- src/App.vue
> 🎉 init/GitHubPR2: PR룰 테스트 2

- src/pages/HomePage.vue
- src/router/index.js
> fix: 라우터 오류 수정

- package.json
- pnpm-lock.yaml
- postcss.config.js
- src/App.vue
- src/api/axiosInstance.js
- src/config/supabase.js
- src/main.js
- src/styles/index.css
- src/styles/tailwind.css
- tailwind.config.js
- tailwind 설치 + 기초 세팅 완료
- axios 설치 + axiosInstance 베이스 생성(api/axiosInstance.js)
- supabase 설치 + supabase 베이스 생성(config/supabase.js)
- .env에 키값 변수만 만들었는데 이건 톡방에 따로 올리겠습니다!
6-chore패키지-설치#6 
- 잘못 설정한게 있다면 알려주세요! ╰(*°▽°*)╯
> 📝chore: 패키지 설치 및 기초 세팅

- package-lock.json
- package.json
- pnpm-lock.yaml
- src/App.vue
- src/api/auth.js
- src/api/comment.js
- src/api/comment_editor.js
- src/api/post.js
- src/api/post_editor.js
- src/api/search.js
- src/api/user.js
- src/pages/test_api_page_hw/Comment.vue
- src/pages/test_api_page_hw/CreateComments.vue
- src/pages/test_api_page_hw/CreateEdit.vue
- src/pages/test_api_page_hw/Post.vue
- src/pages/test_api_page_hw/SearchPost.vue
- src/pages/test_api_page_hw/UpdatePost.vue
> ✨feat : 수파베이스 게시물관련 API 구현

- src/api/auth.js
- src/api/comment_editor.js
- src/api/imageUpload.js
- src/api/user.js
- src/pages/test_api_page_hw/LoginAndUserTest.vue
- src/pages/test_api_page_hw/UserImage.vue
- src/router/index.js
- 인증, 유저, UserImage 관련 API 모듈을 src/api에 만들었습니다.(auth.js, user.js, imageUpload.js)
- API 테스트용 컴포넌트도 만들었습니다.(LoginAndUserTest.vue, UserImage.vue)
- 12-feat-수파베이스-인증유저정보-관련-api-구현 #12 
(//ω＼＼)b
> ✨ feat: 인증, 유저, UserImage 관련 API 제작 및 테스트 파일 제작작

- src/api/apply.js
- src/api/bookmark.js
- src/api/like.js
- src/api/notifications.js
- src/api에 api모듈을 생성했습니다(apply.js, bookmark.js, like.js, notifications.js)
> ✨ feat: 수파베이스 알림, 좋아요, 북마크, 신청하기 api 구현

- src/api/supabase/bookmark.js
- src/api/supabase/comment_editor.js
- src/api/supabase/post.js
- src/api/supabase/post_editor.js
- src/api/supabase/search.js
- src/api/supabase/user.js
- src/layout/MainLayout.vue
- src/pages/test_api_page_hw/Test.vue
- 파일 내 모든 import문의 경로를 alias(@/) 경로로 통일했습니다.
refactor-alias-change-#24
- 말씀해주신 내용이 router에서 import()문의 경로를 말씀하시는줄 알고 상대경로가 없다고 얘기한건데 모든 파일의 import문을 말씀하신 거였군요..!
- 여태껏 작업하면서 경로 통일을 안 하고 막 작성했었는데 앞으로는 import문 통일하는 것도 신경써야 할 거 같습니당 👍👍👍
- 덕분에 또 하나 배워갑니다!!!🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️
> refactor : import문 alias경로로 통일

- src/layout/header/components/HeaderDropdown.vue
- src/layout/header/components/LoggedInRight.vue
latout/header/components/HeaderDropdown.vue 추가
latout/header/components/LoggedInRight.vue 수정
> 💄 style: 헤더 프로필 드롭다운 퍼블리싱

- index.html
- src/pages/ErrorPage.vue
- src/router/index.js
- src/styles/fonts.css
- src/styles/index.css
- src/styles/tailwind.css
- tailwind.config.js
- resolved #51 
- 404 페이지 퍼블리싱
- 폰트 설정 변경 및 "여기어때 잘난체" 폰트 추가
- style-404-#51
> style: 404 페이지 퍼블리싱

- src/components/BaseModal.vue
- src/components/LoginModal.vue
- src/pages/RecruitPostDetailPage.vue
- src/pages/RecruitPostDetailPage/RecruitPostDetailPage.vue
- src/pages/RecruitPostDetailPage/components/ApplyModal.vue
- src/router/index.js
- resolved #70 
- 프로젝트 신청 모달 퍼블리싱
- style-apply-modal-#70
- 모달 배경이 생각보다 엄청 어둡지 않아서 모달에 집중할 수 있는 스타일 요소가 있었으면 했어요! 그래서 블러를 조금 추가해봤는데 괜찮을까요? 아래는 피그마 이미지인데, 이렇게 보일겁니다!
> style: 프로젝트 신청 모달 퍼블리싱

- src/api/supabase/new_comment.js
- src/pages/test_api_page_hw/LoginAndUserTest.vue
- supabase 댓글 관련 api 구현했습니다.
- src/api/supabase/new_comment.js에 작업했습니다.
- 댓글 작성, 수정, 삭제, 포스트 댓글 가져오기 만들었습니다.
- api명세에 댓글 기능 명세 업데이트 했습니당 https://www.notion.so/API-741638f560dd4619bf3c876844ed8964?pvs=4
- 수정해야 하거나 더 필요하신 api 있으시다면 언제든 말씀해주세요!!
- feat-supabase-commentApi-#77
(●'◡'●)
> ✨ feat : supabase 댓글 api 구현

- src/api/supabase/like_and_bookmark.js
- src/pages/test_api_page_hw/LoginAndUserTest.vue
- user_list테이블의 likes column -> post_like테이블로 분리했습니다.
- 기존 함수들도 새로운 테이블에 맞춰 수정했습니다.(기존의 likes 데이터는 전부 지워졌습니다.)
- getPostLikes 함수를 추가했습니다.(특정 post 좋아요 모두 가져오는 함수)
- fix-like-supabase-#84
(❁´◡`❁)
> 🚨 fix : 수파베이스 데이터베이스 구조 변경 + api 추가 및 수정

- src/pages/OnboardPage/OnboardPage.vue
- src/pages/OnboardPage/components/OnboardStep2.vue
- src/pages/OnboardPage/components/OnboardingCompleteModal.vue
1. 버튼 비활성화 상태에서 클릭되는 문제 해결
` if (!isFormValid.value) return`
폼 유효성검사 안 된 상태에서 클릭시 return 추가
2. Vue Router에서 뒤로가기 기록 삭제 (replace: true 적용)
- #105
> fix: 온보딩 버튼 비활, 완료 모달 라우트 수정

- package.json
- src/api/supabase/notifications.js
- src/components/notification/AllNotifications.vue
- src/components/notification/NotificationModal.vue
- src/components/notification/UnWatchedNotifications.vue
- src/layout/header/components/LoggedInRight.vue
- src/pages/EditRecruitPostPage/EditRecruitPostPage.vue
- src/pages/EditRecruitPostPage/components/thirdInfo/EditDetailInfo.vue
- src/pages/EditRecruitPostPage/index.js
- src/pages/RecruitPostDetailPage/components/PostComment.vue
- 알림기능 이용시 모든 유저에게 알림 전송가는 오류 수정
- 로그아웃 후에도 알림 구독이 안 풀리던 문제 해결
- 글 작성 완료 후 작성글 보러가기 클릭시 해당 작성글 페이지로 이동하도록 변경
- 프로젝트 세부내용 제목란 스타일 적용안되던 현상 수정
- 댓글 수정취소시 정상적으로 취소가 되지 않던 현상 수정
- 댓글 유저정보 클릭시 유저정보 모달창과 연결완료
- 알림 모달창 시간표시 추가
- fix-errors-#107
- 오류잡기 100트 OwO
> fix : 각종 에러, 수정사항 해결완료

- src/pages/EditProfilePage/EditProfilePage.vue
- src/pages/Mypage/MyPage.vue
- src/pages/Mypage/components/MyInfo.vue
- resolved #112 
- 프로필 수정 이후 반영이 안되는 문제 해결
- 프로필 수정 시, 스킬 하나도 선택하지 않아도 완료되는 문제 해결 (제가 놓쳤었네용)
- fix-profile-update-#112
> fix: 프로필 수정 이후 반영이 안되는 문제 해결

- src/api/supabase/notifications.js
- src/layout/header/components/LoggedInRight.vue
- src/pages/EditProfilePage/components/DefaultInformation.vue
- src/pages/EditProfilePage/components/ProfileIntroduction.vue
- src/pages/Mypage/MyPage.vue
- src/pages/Mypage/components/MyInfo.vue
- src/stores/notificaionModal.js
- resolved #117 
- 마이페이지 글자 수 제한 설정 누락 추가
- 프로필 이미지 css 관련 오류 수정
- 알림 관련 로직에서 console.log를 삭제했습니다. (현우님 요청)
- 자기소개 글자수 제한 로직을 수정하다 발견한 문제점 입니다.
- 자기소개의 줄바꿈이 반영이 안되거나 영역을 넘어가는 문제가 있어서 함께 해결했습니다!
- fix-text-length-limit-#117
> fix: 마이페이지 글자 수 제한 설정 누락 추가

- src/pages/Mypage/components/LargePostCard.vue
- src/pages/Mypage/components/MyBookmark.vue
- src/pages/Mypage/components/MyRecruitmentList.vue
- src/pages/UserPage/components/UserRecruitmentList.vue
>  fix: 필터링 관련 오류 최종수정

- src/components/UserProfileModal.vue
- 비회원일때 유저닉네임 또는 유저프로필사진 클릭시 유저프로필모달이 보일 수 있게 코드 추가했습니다.
- 비회원일 때는 로그인하고 더 보기 로 버튼을 만들어 로그인을 할수 있게 로그인모달연결시켰습니다.
- #141 
- 보시고 수정사항이 있다면 말씀부탁드립니다~!
> ✨ feat : 비회원일시 유저프로필 모달 조회 기능 추가

- src/components/UserProfileModal.vue
- 비회원일 때 와 회원일때 유저프로필 모달 로직 수정했습니다.
-  feat-non-member-userprofilemodal-view
> 🚨fix: 회원/비회원 유저 프로필 모달 로직 수정

- src/components/UserProfileModal.vue
> 유저프로필 모달 중복 코드 삭제

- src/components/UserProfileModal.vue
> 모달페이지 예지님 파일로 초기화
